import React, { useEffect, useState } from "react";
import { api, type Bootstrap } from "./api";
import { operationsApi, type CustomerHistoryData } from "./operations-api";
import { CustomerProfileActions } from "./customer-profile-actions";

const money=(value:number)=>`S/ ${value.toFixed(2)}`;

export function CustomerManager({data,onChanged,onOpenOrder}:{data:Bootstrap;onChanged:()=>Promise<void>;onOpenOrder:(id:string)=>void|Promise<void>}){
  const [selectedId,setSelectedId]=useState<string|null>(null);const [history,setHistory]=useState<CustomerHistoryData|null>(null);const [loading,setLoading]=useState(false);
  const [name,setName]=useState("");const [phone,setPhone]=useState("");const [instagramHandle,setInstagramHandle]=useState("");const [notes,setNotes]=useState("");const [details,setDetails]=useState(false);const [saving,setSaving]=useState(false);const [error,setError]=useState("");const [success,setSuccess]=useState("");

  const loadHistory=async(id:string)=>{setLoading(true);setError("");try{setHistory(await operationsApi.customerHistory(id));setSelectedId(id);}catch(err){setError(err instanceof Error?err.message:"No se pudo cargar la ficha.");setHistory(null);}finally{setLoading(false);}};
  useEffect(()=>{if(selectedId&&!data.customers.some((row)=>row.id===selectedId)){setSelectedId(null);setHistory(null);}},[data.customers,selectedId]);

  if(selectedId&&history){
    const customer=data.customers.find((row)=>row.id===selectedId)??history.customer;const m=history.metrics;
    return <div className="stack"><section><div className="actions"><button className="ghost" type="button" onClick={()=>{setSelectedId(null);setHistory(null);}}>← Clientes</button></div><h2>{customer.name}</h2><p className="muted">{customer.phone||"Sin teléfono"}{customer.instagramHandle?` · ${customer.instagramHandle}`:""}</p>{customer.notes&&<p>{customer.notes}</p>}
      <CustomerProfileActions customer={customer} onChanged={async()=>{await onChanged();await loadHistory(customer.id);}} onArchived={async()=>{setSelectedId(null);setHistory(null);await onChanged();}} />
    </section><section className="metrics"><div className="metric"><span>Pedidos</span><strong>{m.totalOrders}</strong></div><div className="metric"><span>Activos</span><strong>{m.activeOrders}</strong></div><div className="metric"><span>Vendido</span><strong>{money(m.totalSales)}</strong></div><div className="metric"><span>Cobrado</span><strong>{money(m.totalPaid)}</strong></div><div className="metric"><span>Por cobrar</span><strong>{money(m.balance)}</strong></div></section>
    <section><h2>Historial</h2><p className="muted">Última compra: {m.lastOrderDate??"-"}. Se consulta el historial completo del cliente, no solo los pedidos recientes.</p>{history.orders.length?<div className="list">{history.orders.map((order)=><button className="row" type="button" key={order.id} onClick={()=>void onOpenOrder(order.id)}><span><strong>{order.orderNumber}</strong><small>{order.orderDate} · {order.status}</small></span><span><strong>{money(Number(order.agreedTotalPrice))}</strong><small>pagado {money(order.totalPaid)} · saldo {money(order.balance)}</small></span></button>)}</div>:<p className="muted">Sin pedidos.</p>}</section></div>;
  }

  return <div className="stack"><section><h2>Nuevo cliente</h2><form className="form" onSubmit={async(event)=>{event.preventDefault();setError("");setSuccess("");if(name.trim().length<2)return setError("Ingresa un nombre de al menos 2 caracteres.");setSaving(true);try{await api.createCustomer({name:name.trim(),phone:phone.trim()||null,instagramHandle:instagramHandle.trim()||null,notes:notes.trim()||null});setName("");setPhone("");setInstagramHandle("");setNotes("");setDetails(false);await onChanged();setSuccess("Cliente creado correctamente.");}catch(err){setError(err instanceof Error?err.message:"No se pudo crear el cliente.");}finally{setSaving(false);}}}><label>Nombre *<input name="customer-name" autoComplete="name" value={name} minLength={2} required onChange={(e)=>setName(e.target.value)}/></label><label>Teléfono / WhatsApp <span className="label-optional">opcional</span><input name="customer-phone" autoComplete="tel" value={phone} onChange={(e)=>setPhone(e.target.value)}/></label><button className="disclosure" type="button" aria-expanded={details} onClick={()=>setDetails((current)=>!current)}>{details?"Ocultar detalles":"Más detalles"} <span>{details?"▴":"▾"}</span></button>{details&&<div className="details-panel"><label>Instagram <span className="label-optional">opcional</span><input name="customer-instagram" autoComplete="off" value={instagramHandle} onChange={(e)=>setInstagramHandle(e.target.value)}/></label><label>Notas <span className="label-optional">opcional</span><input name="customer-notes" autoComplete="off" value={notes} onChange={(e)=>setNotes(e.target.value)}/></label></div>}{error&&<p className="error" role="alert">{error}</p>}{success&&<p className="login-success" role="status">{success}</p>}<button disabled={saving||name.trim().length<2}>{saving?"Guardando...":"Crear cliente"}</button></form></section>
    <section><h2>Clientes</h2>{loading&&<p className="muted">Cargando ficha...</p>}{data.customers.length?<div className="list">{data.customers.map((customer)=><button className="row" type="button" key={customer.id} onClick={()=>void loadHistory(customer.id)}><span><strong>{customer.name}</strong><small>{customer.phone||customer.instagramHandle||"Sin contacto"}</small></span><span>Ver ficha</span></button>)}</div>:<p className="muted">Todavía no hay clientes.</p>}</section></div>;
}
