import React, { useEffect, useState } from "react";
import { localDateInputValue } from "../domain/workshop";
import type { Bootstrap } from "./api";
import { operationsApi, type ExpenseRow, type PurchaseRow } from "./operations-api";

const methods = [["YAPE","Yape"],["PLIN","Plin"],["CASH","Efectivo"],["BANK_TRANSFER","Transferencia"],["OTHER","Otro"]] as const;
const expenseCategories = [["EMBROIDERY","Bordado"],["TRANSPORT","Transporte"],["PACKAGING","Empaque"],["TOOLS","Herramientas"],["SERVICES","Servicios"],["MARKETING","Marketing"],["OTHER","Otro"]] as const;
const money = (value: number | string) => `S/ ${Number(value).toFixed(2)}`;
type PurchaseLineForm = { id?: string; materialId: string; quantity: number; totalCost: number };

export function FinanceManager({ data, onChanged }: { data: Bootstrap; onChanged: () => Promise<void> }) {
  const [purchases, setPurchases] = useState<PurchaseRow[]>([]); const [expenses, setExpenses] = useState<ExpenseRow[]>([]); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const [purchaseId, setPurchaseId] = useState<string | null>(null); const [purchaseDate, setPurchaseDate] = useState(localDateInputValue()); const [supplier, setSupplier] = useState(""); const [purchaseMethod, setPurchaseMethod] = useState("YAPE"); const [purchaseNotes, setPurchaseNotes] = useState(""); const [lines, setLines] = useState<PurchaseLineForm[]>([{ materialId: data.materials[0]?.id ?? "", quantity: 1, totalCost: 0 }]);
  const [expenseId, setExpenseId] = useState<string | null>(null); const [expenseDate, setExpenseDate] = useState(localDateInputValue()); const [category, setCategory] = useState("OTHER"); const [description, setDescription] = useState(""); const [amount, setAmount] = useState(0); const [expenseMethod, setExpenseMethod] = useState("YAPE"); const [orderId, setOrderId] = useState(""); const [expenseNotes, setExpenseNotes] = useState("");

  const load = async () => { const [p,e] = await Promise.all([operationsApi.purchases(), operationsApi.expenses()]); setPurchases(p.rows); setExpenses(e.rows); };
  useEffect(() => { void load().catch((err) => setError(err instanceof Error ? err.message : "No se pudieron cargar compras y gastos.")); }, []);
  const resetPurchase = () => { setPurchaseId(null); setPurchaseDate(localDateInputValue()); setSupplier(""); setPurchaseMethod("YAPE"); setPurchaseNotes(""); setLines([{ materialId: data.materials[0]?.id ?? "", quantity: 1, totalCost: 0 }]); };
  const resetExpense = () => { setExpenseId(null); setExpenseDate(localDateInputValue()); setCategory("OTHER"); setDescription(""); setAmount(0); setExpenseMethod("YAPE"); setOrderId(""); setExpenseNotes(""); };

  const editPurchase = (row: PurchaseRow) => { setPurchaseId(row.id); setPurchaseDate(row.purchaseDate); setSupplier(row.supplierName ?? ""); setPurchaseMethod(row.paymentMethod ?? "OTHER"); setPurchaseNotes(row.notes ?? ""); setLines(row.lines.map((line) => ({ id: line.id, materialId: line.materialId, quantity: Number(line.quantity), totalCost: Number(line.totalCost) }))); setError(""); setMessage(""); };
  const editExpense = (row: ExpenseRow) => { setExpenseId(row.id); setExpenseDate(row.expenseDate); setCategory(row.category); setDescription(row.description); setAmount(row.amount); setExpenseMethod(row.paymentMethod ?? "OTHER"); setOrderId(row.orderId ?? ""); setExpenseNotes(row.notes ?? ""); setError(""); setMessage(""); };

  return <div className="stack">
    <section><h2>{purchaseId ? "Editar compra" : "Nueva compra de materiales"}</h2>{!data.materials.length ? <p className="warning">Primero registra materiales en Inventario.</p> : <form className="form" onSubmit={async (event) => { event.preventDefault(); setError(""); setMessage(""); try {
      if (lines.some((line) => !line.materialId || line.quantity <= 0 || line.totalCost <= 0)) throw new Error("Completa material, cantidad y costo de todas las líneas.");
      if (purchaseId) await operationsApi.updatePurchase({ id: purchaseId, purchaseDate, supplierName: supplier || null, paymentMethod: purchaseMethod, notes: purchaseNotes || null, lines: lines.map((line) => ({ id: line.id, quantity: line.quantity, totalCost: line.totalCost })) });
      else await operationsApi.createPurchase({ purchaseDate, supplierName: supplier || null, paymentMethod: purchaseMethod, notes: purchaseNotes || null, lines: lines.map(({ materialId, quantity, totalCost }) => ({ materialId, quantity, totalCost })) });
      resetPurchase(); await Promise.all([load(), onChanged()]); setMessage(purchaseId ? "Compra actualizada." : "Compra registrada y stock actualizado.");
    } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar la compra."); } }}>
      <label>Fecha<input type="date" value={purchaseDate} onChange={(e) => setPurchaseDate(e.target.value)} required /></label><label>Proveedor<input value={supplier} onChange={(e) => setSupplier(e.target.value)} placeholder="Opcional" /></label><label>Método<select value={purchaseMethod} onChange={(e) => setPurchaseMethod(e.target.value)}>{methods.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label>
      <div className="stack compact">{lines.map((line,index) => <div className="form-grid" key={line.id ?? index}><label>Material<select disabled={Boolean(purchaseId)} value={line.materialId} onChange={(e) => setLines((current) => current.map((item,i) => i===index ? { ...item, materialId:e.target.value } : item))}>{data.materials.map((m) => <option key={m.id} value={m.id}>{m.name}{m.color ? ` · ${m.color}` : ""}</option>)}</select></label><label>Cantidad<input type="number" min="0.001" step="0.001" value={line.quantity} onChange={(e) => setLines((current) => current.map((item,i) => i===index ? { ...item, quantity:Number(e.target.value) } : item))} /></label><label>Costo total<input type="number" min="0.01" step="0.01" value={line.totalCost} onChange={(e) => setLines((current) => current.map((item,i) => i===index ? { ...item, totalCost:Number(e.target.value) } : item))} /></label>{!purchaseId && lines.length > 1 && <button className="ghost danger" type="button" onClick={() => setLines((current) => current.filter((_,i) => i!==index))}>Quitar</button>}</div>)}</div>
      {!purchaseId && <button className="secondary" type="button" onClick={() => setLines((current) => [...current,{ materialId:data.materials[0]?.id ?? "",quantity:1,totalCost:0 }])}>Agregar material</button>}
      <label>Notas<input value={purchaseNotes} onChange={(e) => setPurchaseNotes(e.target.value)} /></label><div className="actions"><button>{purchaseId ? "Guardar compra" : "Registrar compra"}</button>{purchaseId && <button className="secondary" type="button" onClick={resetPurchase}>Cancelar</button>}</div>
    </form>}{error && <p className="error" role="alert">{error}</p>}{message && <p className="login-success" role="status">{message}</p>}</section>

    <section><h2>Compras</h2>{purchases.length ? <div className="list">{purchases.map((row) => <div className="row static" key={row.id}><span><strong>{row.purchaseDate} · {row.supplierName || "Sin proveedor"}</strong><small>{row.lines.map((line) => `${line.materialName} ${Number(line.quantity)}`).join(" · ")}</small></span><span><strong>{money(row.totalAmount)}</strong><button className="ghost" onClick={() => editPurchase(row)}>Editar</button><button className="ghost danger" onClick={async () => { if (!confirm("¿Borrar esta compra y revertir su entrada de stock?")) return; try { await operationsApi.archivePurchase(row.id); await Promise.all([load(),onChanged()]); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo borrar la compra."); } }}>Borrar</button></span></div>)}</div> : <p className="muted">Sin compras registradas.</p>}</section>

    <section><h2>{expenseId ? "Editar gasto" : "Nuevo gasto"}</h2><form className="form" onSubmit={async (event) => { event.preventDefault(); setError(""); setMessage(""); try { await operationsApi.saveExpense({ action: expenseId ? "update" : "create", ...(expenseId ? { id:expenseId } : {}), expenseDate, category, description, amount, paymentMethod:expenseMethod, orderId:orderId || null, notes:expenseNotes || null }); const wasEditing=Boolean(expenseId); resetExpense(); await load(); setMessage(wasEditing ? "Gasto actualizado." : "Gasto registrado."); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar el gasto."); } }}>
      <label>Fecha<input type="date" value={expenseDate} onChange={(e) => setExpenseDate(e.target.value)} required /></label><label>Categoría<select value={category} onChange={(e) => setCategory(e.target.value)}>{expenseCategories.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>Descripción<input value={description} onChange={(e) => setDescription(e.target.value)} minLength={2} required /></label><label>Importe<input type="number" min="0.01" step="0.01" value={amount} onChange={(e) => setAmount(Number(e.target.value))} required /></label><label>Método<select value={expenseMethod} onChange={(e) => setExpenseMethod(e.target.value)}>{methods.map(([v,l]) => <option key={v} value={v}>{l}</option>)}</select></label><label>Pedido asociado<select value={orderId} onChange={(e) => setOrderId(e.target.value)}><option value="">Ninguno</option>{data.orders.map((o) => <option key={o.id} value={o.id}>{o.orderNumber} · {o.customerName}</option>)}</select></label><label>Notas<input value={expenseNotes} onChange={(e) => setExpenseNotes(e.target.value)} /></label><div className="actions"><button>{expenseId ? "Guardar gasto" : "Registrar gasto"}</button>{expenseId && <button className="secondary" type="button" onClick={resetExpense}>Cancelar</button>}</div>
    </form></section>

    <section><h2>Gastos</h2>{expenses.length ? <div className="list">{expenses.map((row) => <div className="row static" key={row.id}><span><strong>{row.expenseDate} · {row.description}</strong><small>{row.category}{row.orderNumber ? ` · ${row.orderNumber}` : ""}</small></span><span><strong>{money(row.amount)}</strong><button className="ghost" onClick={() => editExpense(row)}>Editar</button><button className="ghost danger" onClick={async () => { if (!confirm("¿Borrar este gasto?")) return; try { await operationsApi.archiveExpense(row.id); await load(); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo borrar el gasto."); } }}>Borrar</button></span></div>)}</div> : <p className="muted">Sin gastos registrados.</p>}</section>
  </div>;
}
