import React, { useState } from "react";
import { api, type Bootstrap, type Material } from "./api";
import { ArchiveButton } from "./archive-button";
import { getCapturePreferences, rememberMaterialPreferences } from "./capture-preferences";

const categoryLabels: Record<string, string> = { FABRIC: "Tela", CLOSURE: "Cierre", THREAD: "Hilo", PACKAGING: "Empaque", OTHER: "Otro" };
const unitLabels: Record<string, string> = { METER: "m", EACH: "unid.", SPOOL: "carrete", UNIT: "unid." };

export function InventoryManager({ data, onChanged }: { data: Bootstrap; onChanged: () => Promise<void> }) {
  const remembered = getCapturePreferences().material;
  const [editingId, setEditingId] = useState<string | null>(null);
  const [name, setName] = useState(""); const [category, setCategory] = useState(remembered?.category || "FABRIC"); const [unit, setUnit] = useState(remembered?.unit || "METER"); const [color, setColor] = useState(""); const [minimumStock, setMinimumStock] = useState(0); const [initialQuantity, setInitialQuantity] = useState(0); const [initialUnitCost, setInitialUnitCost] = useState(0); const [details, setDetails] = useState(false); const [selectedId, setSelectedId] = useState(""); const [entryQuantity, setEntryQuantity] = useState(0); const [entryUnitCost, setEntryUnitCost] = useState(0); const [message, setMessage] = useState(""); const [error, setError] = useState(""); const [saving, setSaving] = useState(false);

  const changeCategory = (next: string) => { setCategory(next); if (!editingId) setUnit(next === "FABRIC" ? "METER" : next === "THREAD" ? "SPOOL" : "EACH"); };
  const resetMaterial = () => { const preferences = getCapturePreferences().material; setEditingId(null); setName(""); setCategory(preferences?.category || "FABRIC"); setUnit(preferences?.unit || "METER"); setColor(""); setMinimumStock(0); setInitialQuantity(0); setInitialUnitCost(0); setDetails(false); };
  const editMaterial = (material: Material) => { setEditingId(material.id); setName(material.name); setCategory(material.category); setUnit(material.unit); setColor(material.color ?? ""); setMinimumStock(Number(material.minimumStock ?? 0)); setInitialQuantity(0); setInitialUnitCost(0); setDetails(true); setError(""); setMessage(""); };

  const saveMaterial = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setMessage(""); if (name.trim().length < 2) return setError("Ingresa un nombre para el material."); setSaving(true); try { await api.createMaterial(editingId ? { action: "update", id: editingId, name: name.trim(), category, unit, color: color.trim() || null, minimumStock } : { name: name.trim(), category, unit, color: color.trim() || null, minimumStock, initialQuantity, unitCost: initialQuantity > 0 ? initialUnitCost : null }); const wasEditing = Boolean(editingId); if (!wasEditing) rememberMaterialPreferences({ category, unit }); resetMaterial(); await onChanged(); setMessage(wasEditing ? "Material actualizado correctamente." : "Material creado correctamente."); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo guardar el material."); } finally { setSaving(false); } };
  const addStock = async (event: React.FormEvent<HTMLFormElement>) => { event.preventDefault(); setError(""); setMessage(""); if (!selectedId || entryQuantity <= 0) return setError("Selecciona un material e ingresa una cantidad mayor a cero."); setSaving(true); try { await api.addMaterialStock(selectedId, { quantity: entryQuantity, unitCost: entryUnitCost }); setEntryQuantity(0); setEntryUnitCost(0); await onChanged(); setMessage("Entrada registrada correctamente."); } catch (err) { setError(err instanceof Error ? err.message : "No se pudo registrar la entrada."); } finally { setSaving(false); } };

  return <div className="stack"><section><h2>{editingId ? "Editar material" : "Nuevo material"}</h2><form className="form" onSubmit={saveMaterial}>
    <div className="form-grid"><label>Material *<input autoFocus value={name} onChange={(e) => setName(e.target.value)} required minLength={2} placeholder="Ej. Tela azul" /></label><label>Tipo<select value={category} onChange={(e) => changeCategory(e.target.value)}>{Object.entries(categoryLabels).map(([value,label]) => <option key={value} value={value}>{label}</option>)}</select></label><label>Unidad<select value={unit} onChange={(e) => setUnit(e.target.value)}><option value="METER">Metro</option><option value="EACH">Unidad</option><option value="SPOOL">Carrete</option><option value="UNIT">Otra unidad</option></select></label></div>
    <button className="disclosure" type="button" aria-expanded={details} onClick={() => setDetails((current) => !current)}>{details ? "Ocultar detalles" : "Más detalles"} <span>{details ? "▴" : "▾"}</span></button>
    {details && <div className="details-panel"><label>Color <span className="label-optional">opcional</span><input value={color} onChange={(e) => setColor(e.target.value)} /></label><label>Stock mínimo <span className="label-optional">opcional</span><input type="number" min="0" step="0.01" value={minimumStock} onChange={(e) => setMinimumStock(Number(e.target.value))} /></label>{!editingId && <><label>Stock inicial <span className="label-optional">opcional</span><input type="number" min="0" step="0.01" value={initialQuantity} onChange={(e) => setInitialQuantity(Number(e.target.value))} /></label>{initialQuantity > 0 && <label>Costo por unidad<input type="number" min="0" step="0.01" value={initialUnitCost} onChange={(e) => setInitialUnitCost(Number(e.target.value))} /></label>}</>}{editingId && <p className="muted">El stock se corrige mediante movimientos; al editar no se reescribe la cantidad histórica.</p>}</div>}
    {error && <p className="error" role="alert">{error}</p>}{message && <p className="login-success" role="status">{message}</p>}<div className="actions"><button type="submit" disabled={saving || name.trim().length < 2}>{saving ? "Guardando..." : editingId ? "Guardar cambios" : "Crear material"}</button>{editingId && <button className="secondary" type="button" onClick={resetMaterial}>Cancelar</button>}</div>
  </form></section>{!!data.materials.length && <section><h2>Registrar entrada</h2><form className="form" onSubmit={addStock}><label>Material<select value={selectedId} onChange={(e) => setSelectedId(e.target.value)}><option value="">Selecciona...</option>{data.materials.map((m) => <option key={m.id} value={m.id}>{m.name} · {m.currentQuantity} {unitLabels[m.unit] ?? m.unit}</option>)}</select></label><label>Cantidad<input type="number" min="0.01" step="0.01" value={entryQuantity} onChange={(e) => setEntryQuantity(Number(e.target.value))} /></label><label>Costo por unidad<input type="number" min="0" step="0.01" value={entryUnitCost} onChange={(e) => setEntryUnitCost(Number(e.target.value))} /></label><button type="submit" disabled={saving || !selectedId || entryQuantity <= 0}>{saving ? "Guardando..." : "Registrar entrada"}</button></form></section>}
    <section><h2>Inventario</h2>{!data.materials.length ? <p className="muted">Todavía no hay materiales registrados.</p> : <div className="list">{data.materials.map((m) => <div className="row static" key={m.id}><span><strong>{m.name}</strong><small>{categoryLabels[m.category] ?? m.category} · {m.color ?? "sin color"}</small></span><span><strong>{m.currentQuantity} {unitLabels[m.unit] ?? m.unit}</strong><button className="ghost" type="button" onClick={() => editMaterial(m)}>Editar</button><ArchiveButton entityType="MATERIAL" id={m.id} onArchived={onChanged} /></span></div>)}</div>}</section></div>;
}
