import { getToken } from "./api";

export type SizeConsumptionRow = { productId: string; size: string; fabricQtyMeters: number | null };
export type ProviderRow = { id: string; name: string; phone?: string | null; notes?: string | null };
export type StockEntryRow = { id: string; materialId: string; materialName: string; type: string; quantitySigned: number; unitCost?: number | null; notes?: string | null; occurredAt: string };
export type PurchaseRow = { id: string; purchaseDate: string; supplierName?: string | null; totalAmount: number; paymentMethod?: string | null; notes?: string | null; lines: Array<{ id: string; materialId: string; materialName: string; quantity: number | string; totalCost: number | string; unitCost: number | string }> };
export type ExpenseRow = { id: string; expenseDate: string; category: string; description: string; amount: number; paymentMethod?: string | null; orderId?: string | null; orderNumber?: string | null; notes?: string | null };
export type MoneySummary = { month: string; sales: number; collected: number; purchases: number; expenses: number; receivable: number; netCash: number };
export type FinishedStockData = { balances: Array<{ productId: string; productName: string; size: string; color: string; quantity: number }>; movements: Array<{ id: string; productId: string; size: string; color: string; type: string; quantitySigned: number; unitCost?: number | null; notes?: string | null; occurredAt: string }> };
export type AgendaData = { orders: Array<{ id: string; orderNumber: string; status: string; promisedDeliveryDate: string; customerName: string; phone?: string | null; agreedTotalPrice: number; balance: number }>; embroidery: Array<{ id: string; status: string; expectedReturnDate?: string | null; sentAt?: string | null; orderId: string; orderNumber: string; customerName: string; providerName: string; providerPhone?: string | null }> };

async function request<T>(path:string,options:RequestInit={}){const token=getToken();const response=await fetch(path,{...options,headers:{"content-type":"application/json",...(token?{authorization:`Bearer ${token}`}:{ }),...options.headers}});const payload=await response.json().catch(()=>({error:response.statusText}));if(!response.ok)throw new Error(payload.error??"Error de API");return payload as T;}

export const operationsApi={
  sizeConsumption:()=>request<{rows:SizeConsumptionRow[]}>("/api/workshop/size-consumption"),saveSizeConsumption:(productId:string,quantities:Record<string,number|null>)=>request<{rows:SizeConsumptionRow[]}>("/api/workshop/size-consumption",{method:"POST",body:JSON.stringify({productId,quantities})}),
  stockEntries:()=>request<{rows:StockEntryRow[]}>("/api/workshop/stock-entries"),updateStockEntry:(id:string,payload:{quantity:number;unitCost?:number|null;notes?:string|null})=>request<Record<string,unknown>>("/api/workshop/stock-entries",{method:"POST",body:JSON.stringify({action:"update",id,...payload})}),archiveStockEntry:(id:string)=>request<{ok:true}>("/api/workshop/stock-entries",{method:"POST",body:JSON.stringify({action:"archive",id})}),
  finishedStock:()=>request<FinishedStockData>("/api/workshop/finished-stock"),saveFinishedStock:(payload:Record<string,unknown>)=>request<Record<string,unknown>>("/api/workshop/finished-stock",{method:"POST",body:JSON.stringify(payload)}),archiveFinishedStock:(id:string)=>request<{ok:true}>("/api/workshop/finished-stock",{method:"POST",body:JSON.stringify({action:"archive",id})}),
  providers:()=>request<{rows:ProviderRow[]}>("/api/workshop/providers"),saveProvider:(payload:Record<string,unknown>)=>request<ProviderRow>("/api/workshop/providers",{method:"POST",body:JSON.stringify(payload)}),archiveProvider:(id:string)=>request<{ok:true}>("/api/workshop/providers",{method:"POST",body:JSON.stringify({action:"archive",id})}),
  updateEmbroideryJob:(id:string,payload:Record<string,unknown>)=>request<Record<string,unknown>>(`/api/workshop/embroidery-jobs/${id}`,{method:"POST",body:JSON.stringify({action:"update",...payload})}),archiveEmbroideryJob:(id:string)=>request<{ok:true;orderStatus?:string}>(`/api/workshop/embroidery-jobs/${id}`,{method:"POST",body:JSON.stringify({action:"archive"})}),
  purchases:()=>request<{rows:PurchaseRow[]}>("/api/workshop/purchases"),createPurchase:(payload:Record<string,unknown>)=>request<PurchaseRow>("/api/workshop/purchases",{method:"POST",body:JSON.stringify(payload)}),updatePurchase:(payload:Record<string,unknown>)=>request<PurchaseRow>("/api/workshop/purchases",{method:"POST",body:JSON.stringify({action:"update",...payload})}),archivePurchase:(id:string)=>request<{ok:true}>("/api/workshop/purchases",{method:"POST",body:JSON.stringify({action:"archive",id})}),
  expenses:()=>request<{rows:ExpenseRow[]}>("/api/workshop/expenses"),saveExpense:(payload:Record<string,unknown>)=>request<ExpenseRow>("/api/workshop/expenses",{method:"POST",body:JSON.stringify(payload)}),archiveExpense:(id:string)=>request<{ok:true}>("/api/workshop/expenses",{method:"POST",body:JSON.stringify({action:"archive",id})}),
  money:(month?:string)=>request<MoneySummary>(`/api/workshop/money${month?`?month=${encodeURIComponent(month)}`:""}`),agenda:()=>request<AgendaData>("/api/workshop/agenda"),
  startAssembly:(orderId:string)=>request<{ok:true;status:string;consumed:number;alreadyConsumed:boolean}>(`/api/workshop/orders/${orderId}/assembly`,{method:"POST",body:"{}"}),readyForDelivery:(orderId:string)=>request<{ok:true;status:string;consumed:number;alreadyConsumed:boolean}>(`/api/workshop/orders/${orderId}/ready-delivery`,{method:"POST",body:"{}"})
};
