import React, { useEffect, useState } from "react";
import { operationsApi, type ProviderRow } from "./operations-api";

export function ProvidersManager({ onChanged }: { onChanged: () => Promise<void> }) {
  const [rows, setRows] = useState<ProviderRow[]>([]); const [editingId, setEditingId] = useState<string | null>(null); const [name, setName] = useState(""); const [phone, setPhone] = useState(""); const [notes, setNotes] = useState(""); const [error, setError] = useState(""); const [message, setMessage] = useState("");
  const load = async () => { const result = await operationsApi.providers(); setRows(result.rows); };
  useEffect(() => { void load().catch((err) => setError(err instanceof Error ? err.message : "No se pudieron cargar los bordadores.")); }, []);
  const reset = () => { setEditingId(null); setName(""); setPhone(""); setNotes(""); };
  const edit = (row: ProviderRow) => { setEditingId(row.id); setName(row.name); setPhone(row.phone ?? ""); setNotes(row.notes ?? ""); setError(""); setMessage(""); };

  return <div className="stack"><section><h2>{editingId ? "Editar bordador" : "Nuevo bordador"}</h2><form className="form" onSubmit={async (event) => { event.preventDefault(); setError(""); setMessage(""); try { const wasEditing=Boolean(editingId); await operationsApi.saveProvider({ action:wasEditing?"update":"create", ...(editingId?{id:editingId}:{}), name:name.trim(), phone:phone.trim()||null, notes:notes.trim()||null }); reset(); await Promise.all([load(),onChanged()]); setMessage(wasEditing?"Bordador actualizado.":"Bordador registrado."); } catch (err) { setError(err instanceof Error?err.message:"No se pudo guardar el bordador."); } }}>
    <label>Nombre<input value={name} minLength={2} required onChange={(e)=>setName(e.target.value)} /></label><label>Teléfono / WhatsApp<input value={phone} onChange={(e)=>setPhone(e.target.value)} /></label><label>Notas<input value={notes} onChange={(e)=>setNotes(e.target.value)} /></label>{error&&<p className="error" role="alert">{error}</p>}{message&&<p className="login-success" role="status">{message}</p>}<div className="actions"><button>{editingId?"Guardar":"Crear bordador"}</button>{editingId&&<button className="secondary" type="button" onClick={reset}>Cancelar</button>}</div>
  </form></section><section><h2>Bordadores</h2>{rows.length?<div className="list">{rows.map((row)=><div className="row static" key={row.id}><span><strong>{row.name}</strong><small>{row.phone||"Sin teléfono"}{row.notes?` · ${row.notes}`:""}</small></span><span><button className="ghost" onClick={()=>edit(row)}>Editar</button><button className="ghost danger" onClick={async()=>{if(!confirm("¿Borrar este bordador?"))return;try{await operationsApi.archiveProvider(row.id);await Promise.all([load(),onChanged()]);}catch(err){setError(err instanceof Error?err.message:"No se pudo borrar el bordador.");}}}>Borrar</button></span></div>)}</div>:<p className="muted">Todavía no hay bordadores registrados.</p>}</section></div>;
}
